export const CarouselDocs = [
  {
    img1: "/img/webProject/inBest/inBest1.png",
    img2: "/img/webProject/inBest/inBest2.png",
    img3: "/img/webProject/inBest/inBest3.png",
    title: "inBest",
    content: "개인 투자자의 데이터 기반 투자 활성화를\n도모하는 웹 서비스",
    date: "2022.10.07 ~ 2022.10.10",
    stack: "React JS, JavaScript",
    part: "회원가입 페이지 개발\n메인 페이지 (차트) 개발\n서비스 (전체) 디자인 개발",
  },
  {
    img1: "/img/webProject/ROC/ROC1.png",
    img2: "/img/webProject/ROC/ROC2.png",
    img3: "/img/webProject/ROC/ROC3.png",
    title: "ROC",
    content: "챌린지 모집 웹 서비스",
    date: "22022.10 ~ 2022.12",
    stack: "React.js, TypeScript",
    part: "메인 페이지 개발\n챌린지 생성/가입 페이지 개발\n서비스 (전체)디자인 제작",
  },
  {
    img1: "/img/webProject/eng/eng1.png",
    img2: "/img/webProject/eng/eng2.png",
    img3: "/img/webProject/eng/eng3.png",
    title: "지니영어",
    content: "학원 정보 알림 웹 서비스",
    date: "2023.02 ~ 2023.03",
    stack: "Next.js, TypeScript, Recoil",
    part: "회원가입 페이지 개발\n메인 페이지 (차트) 개발\n서비스 (전체) 디자인 개발",
  },
  {
    img1: "/img/webProject/heimer/heimer1.png",
    img2: "/img/webProject/heimer/heimer2.png",
    img3: "/img/webProject/heimer/heimer3.png",
    title: "하이머딩거",
    content: "치매 정보 공유 웹 서비스",
    date: "2023.02 ~ 2023.06(완료 예정)",
    stack: "Next.js, TypeScript, Recoil",
    part: "로그인/회원가입 페이지 개발\n소통 게시판(하이머 소식) 페이지 개발\n치매 예방 프로그램(카드 뒤집기) 개발\n서비스 (전체)디자인 제작",
  },
];
